services:
  api:
    build:
      context: ./ecommerce-backend
    container_name: ecommerce_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-mysql+aiomysql://user:password@db:3306/ecommerce_db}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - db
      - redis
    volumes:
      - ./ecommerce-backend:/app

  db:
    image: mysql:8.0
    container_name: ecommerce_db
    environment:
      - MYSQL_DATABASE=ecommerce_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    container_name: ecommerce_redis
    ports:
      - "6380:6379"

volumes:
  mysql_data:
